/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package demoproject.view;

import java.awt.BorderLayout;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;

/**
 *
 * @author sangyakoirala
 */
public class LoginView extends javax.swing.JFrame {
    boolean isVisible= false;

    /**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();
        setTitle("Login Screen");
        setLayout(new BorderLayout());
        setDefaultCloseOperation(EXIT_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginSubtitleLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        loginSubtitleLabel1 = new javax.swing.JLabel();
        loginSubtitleLabel2 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        showPasswordButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        forgotPasswordLabel = new javax.swing.JLabel();
        noAccountLabel = new javax.swing.JLabel();
        registerLabel = new javax.swing.JLabel();
        demoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        loginSubtitleLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        loginSubtitleLabel.setForeground(new java.awt.Color(25, 25, 112));
        loginSubtitleLabel.setText("Enter your credentials to login");

        emailTextField.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        emailTextField.setForeground(new java.awt.Color(25, 25, 112));
        emailTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emailTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(25, 25, 112), 1, true));

        loginSubtitleLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        loginSubtitleLabel1.setForeground(new java.awt.Color(25, 25, 112));
        loginSubtitleLabel1.setText("Email");

        loginSubtitleLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        loginSubtitleLabel2.setForeground(new java.awt.Color(25, 25, 112));
        loginSubtitleLabel2.setText("Password");

        passwordField.setForeground(new java.awt.Color(25, 25, 112));
        passwordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(25, 25, 112), 1, true));

        showPasswordButton.setText("Show");

        loginButton.setBackground(new java.awt.Color(25, 25, 112));
        loginButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Login");
        loginButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 1, true));

        forgotPasswordLabel.setBackground(new java.awt.Color(0, 153, 153));
        forgotPasswordLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        forgotPasswordLabel.setForeground(new java.awt.Color(255, 51, 0));
        forgotPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forgotPasswordLabel.setText("Forgot Password?");
        forgotPasswordLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotPasswordLabelMouseClicked(evt);
            }
        });

        noAccountLabel.setBackground(new java.awt.Color(0, 153, 153));
        noAccountLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        noAccountLabel.setForeground(new java.awt.Color(51, 51, 51));
        noAccountLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        noAccountLabel.setText("Do not have an account?");

        registerLabel.setBackground(new java.awt.Color(0, 153, 153));
        registerLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        registerLabel.setForeground(new java.awt.Color(51, 102, 255));
        registerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerLabel.setText("Register");

        demoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        demoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepicker/mainLogo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(noAccountLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(registerLabel))
                    .addComponent(forgotPasswordLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginSubtitleLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loginSubtitleLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passwordField)
                            .addComponent(emailTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(loginSubtitleLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(loginButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(showPasswordButton)
                .addGap(79, 79, 79))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(demoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(demoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(loginSubtitleLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginSubtitleLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginSubtitleLabel2)
                    .addComponent(showPasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(forgotPasswordLabel)
                .addGap(18, 18, 18)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noAccountLabel)
                    .addComponent(registerLabel))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void forgotPasswordLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotPasswordLabelMouseClicked
     
    }//GEN-LAST:event_forgotPasswordLabelMouseClicked
    

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel demoLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel forgotPasswordLabel;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginSubtitleLabel;
    private javax.swing.JLabel loginSubtitleLabel1;
    private javax.swing.JLabel loginSubtitleLabel2;
    private javax.swing.JLabel noAccountLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel registerLabel;
    private javax.swing.JButton showPasswordButton;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTextField getEmailTextField(){
        return emailTextField;
    }
     public javax.swing.JPasswordField getPasswordField(){
        return passwordField;
    }
    public void addRegisterListener(MouseListener listener){
        registerLabel.addMouseListener(listener);

    }
    public void addLoginUserListener(ActionListener listener){
        loginButton.addActionListener(listener);
    }

    public void togglePasswordField(boolean visible) {
        passwordField.setEchoChar(visible ? (char) 0 : '*');
        showPasswordButton.setText(visible ? "Hide" : "Show");
    }
    public void showPasswordButtonListener(ActionListener listener){
        showPasswordButton.addActionListener(listener);
    }
    

}
