/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package demoproject.view;

import java.awt.BorderLayout;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.io.File;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;

/**
 *
 * @author sangyakoirala
 */
public class RegistrationView extends javax.swing.JFrame {
    File selectedFile;

    /**
     * Creates new form LoginView
     */
    public RegistrationView() {
        initComponents();
        setTitle("Register Screen");
        setLayout(new BorderLayout());
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginSubtitleLabel3 = new javax.swing.JLabel();
        loginSubtitleLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        showPasswordButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();
        noAccountLabel = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        demoLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        confirmPasswordField = new javax.swing.JPasswordField();
        confirmPasswordLabel = new javax.swing.JLabel();
        showPasswordButton1 = new javax.swing.JButton();
        uploadImageButton = new javax.swing.JButton();

        loginSubtitleLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        loginSubtitleLabel3.setForeground(new java.awt.Color(25, 25, 112));
        loginSubtitleLabel3.setText("Password");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        loginSubtitleLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        loginSubtitleLabel.setForeground(new java.awt.Color(25, 25, 112));
        loginSubtitleLabel.setText("Enter your details to register");

        emailTextField.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        emailTextField.setForeground(new java.awt.Color(25, 25, 112));
        emailTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emailTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(25, 25, 112), 1, true));

        emailLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(25, 25, 112));
        emailLabel.setText("Email");

        passwordLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(25, 25, 112));
        passwordLabel.setText("Password");

        passwordField.setForeground(new java.awt.Color(25, 25, 112));
        passwordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(25, 25, 112), 1, true));

        showPasswordButton.setText("Show");

        registerButton.setBackground(new java.awt.Color(25, 25, 112));
        registerButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        registerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerButton.setText("Register");
        registerButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 1, true));

        noAccountLabel.setBackground(new java.awt.Color(0, 153, 153));
        noAccountLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        noAccountLabel.setForeground(new java.awt.Color(51, 51, 51));
        noAccountLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        noAccountLabel.setText("Already have an account?");

        loginLabel.setBackground(new java.awt.Color(0, 153, 153));
        loginLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(51, 102, 255));
        loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLabel.setText("Login");

        demoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        demoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepicker/mainLogo.png"))); // NOI18N

        nameLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(25, 25, 112));
        nameLabel.setText("Name");

        nameTextField.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        nameTextField.setForeground(new java.awt.Color(25, 25, 112));
        nameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nameTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(25, 25, 112), 1, true));

        confirmPasswordField.setForeground(new java.awt.Color(25, 25, 112));
        confirmPasswordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        confirmPasswordField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(25, 25, 112), 1, true));

        confirmPasswordLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        confirmPasswordLabel.setForeground(new java.awt.Color(25, 25, 112));
        confirmPasswordLabel.setText("Confirm Password");

        showPasswordButton1.setText("Show");

        uploadImageButton.setBackground(new java.awt.Color(0, 102, 255));
        uploadImageButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        uploadImageButton.setForeground(new java.awt.Color(255, 255, 255));
        uploadImageButton.setText("Upload Image");
        uploadImageButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 1, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(229, Short.MAX_VALUE)
                .addComponent(noAccountLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginLabel)
                .addGap(163, 163, 163))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(confirmPasswordLabel)
                                .addGap(37, 37, 37))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(demoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uploadImageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passwordField)
                            .addComponent(emailTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nameTextField)
                            .addComponent(confirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showPasswordButton)
                            .addComponent(showPasswordButton1)))
                    .addComponent(loginSubtitleLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(demoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(loginSubtitleLabel)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLabel)
                    .addComponent(showPasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showPasswordButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(uploadImageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noAccountLabel)
                    .addComponent(loginLabel))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmPasswordField;
    private javax.swing.JLabel confirmPasswordLabel;
    private javax.swing.JLabel demoLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel loginSubtitleLabel;
    private javax.swing.JLabel loginSubtitleLabel3;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel noAccountLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton registerButton;
    private javax.swing.JButton showPasswordButton;
    private javax.swing.JButton showPasswordButton1;
    private javax.swing.JButton uploadImageButton;
    // End of variables declaration//GEN-END:variables

    public void addRegisterUserListener(ActionListener listener) {
        registerButton.addActionListener(listener);
    }
    public void togglePasswordField(boolean visible) {
        passwordField.setEchoChar(visible ? (char) 0 : '*');
        showPasswordButton.setText(visible ? "Hide" : "Show");
    }

    public void toggleConfirmPasswordField(boolean visible) {
        confirmPasswordField.setEchoChar(visible ? (char) 0 : '*');
        showPasswordButton1.setText(visible ? "Hide" : "Show");
    }

    public void addLoginListener(MouseListener listener){
        loginLabel.addMouseListener(listener);
    }
    
    public void showPasswordButtonListener(ActionListener listener){
        showPasswordButton.addActionListener(listener);
    }
    
    public void showPasswordButton1Listener(ActionListener listener){
        showPasswordButton1.addActionListener(listener);
    }
    public void uploadImageButtonListener(ActionListener listener){
        uploadImageButton.addActionListener(listener);
    }

    public void setSelectedFile(File file) {
        this.selectedFile = file;
    }
    
    public javax.swing.JTextField getNameTextField(){
        return nameTextField;
    }
    
    public javax.swing.JTextField getEmailTextField(){
        return emailTextField;
    }
    
    public javax.swing.JPasswordField getPasswordField(){
            return passwordField;
    }
    
    public javax.swing.JPasswordField getConfirmPasswordField(){
        return confirmPasswordField;
    }
    
    public File getSelectedFile(){
        return selectedFile;
    }
   

}
